// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: client_info.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceType int32

const (
	SourceType_UNSPECIFIED    SourceType = 0
	SourceType_BLUE_UI_SYSTEM SourceType = 1
	SourceType_BLUE_UI_USER   SourceType = 2
	SourceType_CLI            SourceType = 3
	SourceType_JOBS           SourceType = 4
	SourceType_STATISTICS     SourceType = 5
	SourceType_EXTERNAL       SourceType = 6
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "BLUE_UI_SYSTEM",
		2: "BLUE_UI_USER",
		3: "CLI",
		4: "JOBS",
		5: "STATISTICS",
		6: "EXTERNAL",
	}
	SourceType_value = map[string]int32{
		"UNSPECIFIED":    0,
		"BLUE_UI_SYSTEM": 1,
		"BLUE_UI_USER":   2,
		"CLI":            3,
		"JOBS":           4,
		"STATISTICS":     5,
		"EXTERNAL":       6,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_info_proto_enumTypes[0].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_client_info_proto_enumTypes[0]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_client_info_proto_rawDescGZIP(), []int{0}
}

type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    string     `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	SourceType SourceType `protobuf:"varint,2,opt,name=source_type,json=sourceType,proto3,enum=com.sqream.cloud.generated.v1.SourceType" json:"source_type,omitempty"`
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_client_info_proto_rawDescGZIP(), []int{0}
}

func (x *ClientInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClientInfo) GetSourceType() SourceType {
	if x != nil {
		return x.SourceType
	}
	return SourceType_UNSPECIFIED
}

var File_client_info_proto protoreflect.FileDescriptor

var file_client_info_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x71, 0x72, 0x65, 0x61, 0x6d, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2e,
	0x76, 0x31, 0x22, 0x72, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x0b, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x71, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x74, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x42, 0x4c, 0x55, 0x45, 0x5f, 0x55, 0x49,
	0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x4c, 0x55,
	0x45, 0x5f, 0x55, 0x49, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x43,
	0x4c, 0x49, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x4f, 0x42, 0x53, 0x10, 0x04, 0x12, 0x0e,
	0x0a, 0x0a, 0x53, 0x54, 0x41, 0x54, 0x49, 0x53, 0x54, 0x49, 0x43, 0x53, 0x10, 0x05, 0x12, 0x0c,
	0x0a, 0x08, 0x45, 0x58, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x10, 0x06, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_info_proto_rawDescOnce sync.Once
	file_client_info_proto_rawDescData = file_client_info_proto_rawDesc
)

func file_client_info_proto_rawDescGZIP() []byte {
	file_client_info_proto_rawDescOnce.Do(func() {
		file_client_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_info_proto_rawDescData)
	})
	return file_client_info_proto_rawDescData
}

var file_client_info_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_client_info_proto_goTypes = []interface{}{
	(SourceType)(0),    // 0: com.sqream.cloud.generated.v1.SourceType
	(*ClientInfo)(nil), // 1: com.sqream.cloud.generated.v1.ClientInfo
}
var file_client_info_proto_depIdxs = []int32{
	0, // 0: com.sqream.cloud.generated.v1.ClientInfo.source_type:type_name -> com.sqream.cloud.generated.v1.SourceType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_client_info_proto_init() }
func file_client_info_proto_init() {
	if File_client_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_info_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_info_proto_goTypes,
		DependencyIndexes: file_client_info_proto_depIdxs,
		EnumInfos:         file_client_info_proto_enumTypes,
		MessageInfos:      file_client_info_proto_msgTypes,
	}.Build()
	File_client_info_proto = out.File
	file_client_info_proto_rawDesc = nil
	file_client_info_proto_goTypes = nil
	file_client_info_proto_depIdxs = nil
}
